### ISSUE TITLE
Dark Shades on Object Texture

### ISSUE THREAD

**Issue by micaeltchapmi** [NVIDIA/VisRTX#19]
Hi,

I'm trying to render a white fabric material (Fabric::Upholstery_Mona::mona_white) on a couch object and I noticed some dark shades on the couch as shown below. 
<img width="282" alt="Screen Shot 2020-06-03 at 11 46 04 AM" src="https://user-images.githubusercontent.com/35488694/83677659-5dc11f80-a591-11ea-82f0-74e3b5baa4ae.png">

Can you help me understand why this is happening? I UV unwrapped the couch in Blender before rendering with VisRTX. I have attached a minimal code to reproduce as well as the object I am trying to render and a slightly modified Sample.h. I run the code with `./visRtxSampleMDLHDRI`
[test_darkshades.zip](https://github.com/NVIDIA/VisRTX/files/4726275/test_darkshades.zip)

OS: Ubuntu 16.04
Optix: NVIDIA-OptiX-SDK-6.0.0-linux64
MDL: MDL-SDK-2019
CUDA Version: 10.2
Driver Version: 440.59

**Comment by progschj** [comment]
Does something similar happen with a simpler material? I looked at the normals and they are essentially diagonal on the edges of the cushion. So they vary quite a bit from one to the other side of the cushions which might cause this change of shading on the otherwise "flat" surfaces.

**Comment by micaeltchapmi** [comment]
Hi progschj,

Thanks for your reply. I tried other simpler materials and observed a similar dark shade. Here is an example with a yellow plastic material. 
<img width="285" alt="Screen Shot 2020-06-05 at 7 46 54 PM" src="https://user-images.githubusercontent.com/35488694/84084464-5e462580-a998-11ea-8fea-47c7698a67f2.png">

I also visualized the normals and saw that they were diagonal at the edges of the cushion but I'm not sure how they affect the shading and what direction they should face to obtain proper shading. Could you please explain that further?

Thanks,

Micael

**Comment by micaeltchapmi** [comment]
Hi progschj,

I was able to get rid of the dark shades on the couch by applying an edge split modifier with an angle of 0 in blender. However, the texture of the material is close but not exactly as what is displayed in the material preview.

Material Preview
<img width="183" alt="Screen Shot 2020-06-11 at 10 53 33 AM" src="https://user-images.githubusercontent.com/35488694/84422448-e06d5e80-abd1-11ea-882f-505360be232b.png">

My couch
<img width="367" alt="Screen Shot 2020-06-11 at 10 39 41 AM" src="https://user-images.githubusercontent.com/35488694/84422489-eebb7a80-abd1-11ea-91f6-6773c4171961.png">

I also tried running the SampleMeshviewer script on the cow.obj you provided with this material (Fabric::Upholstery_Mona::mona_white) but the the texture is not as shown in the material preview.

cow.obj
<img width="296" alt="Screen Shot 2020-06-11 at 10 43 11 AM" src="https://user-images.githubusercontent.com/35488694/84422884-8620cd80-abd2-11ea-988a-575758da4536.png">

Is there a reason why the textures look this different? how can I make my texture look like the preview?

Thanks,

Micael

**Comment by lynetcha** [comment]
@tbiedert  - can you possibly help with the issue above with code attached? We are able to get this working in Blender with materials from [CCOTextures](https://cc0textures.com/)(same uvmap + normals) and we want to get this working with MDL materials as well. Thanks.

**Comment by micaeltchapmi** [comment]
@tbiedert Here is an image of the couch we were able to render in blender using a Fabric material from [CCOTextures](https://cc0textures.com/) with the same uvmap+normals. 
<img width="314" alt="Screen Shot 2020-06-14 at 1 29 06 PM" src="https://user-images.githubusercontent.com/35488694/84603460-85db3900-ae43-11ea-89f9-838a5225f3c2.png"> 
We would like to render it with the MDL materials. We will greatly appreciate your help!

Thanks,

Micael

**Comment by progschj** [comment]
What specifically is the difference that you don't expect? It looks to me the "structure" is coarser (that would depend on texture coordinates I guess?) and they look darker than in the preview. But that is hard to compare just form images without knowing if the lighting is identical etc.

**Comment by micaeltchapmi** [comment]
@progschj - the difference with the reference image is not the primary issue. The main issue we have is with these dark bands appearing on our render.
<img width="282" alt="Screen Shot 2020-06-03 at 11 46 04 AM" src="https://user-images.githubusercontent.com/35488694/83677659-5dc11f80-a591-11ea-82f0-74e3b5baa4ae.png">.
This rendering was generated with this code [test_darkbands.zip](https://github.com/NVIDIA/VisRTX/files/4726275/test_darkshades.zip).

We used the same .obj model to render a PBR materials from CCOTextures and those dark bands do not appear on the rendering so we do not believe the normals or uvmapping are the issue. 
<img width="314" alt="Screen Shot 2020-06-14 at 1 29 06 PM" src="https://user-images.githubusercontent.com/35488694/84603460-85db3900-ae43-11ea-89f9-838a5225f3c2.png"> 

We think this might be related to the MDL/VisRTX rendering itself(maybe the way normals are handled). We rendered an entire scene with an hdri map and MDL materials and almost all objects in the scene have similar dark band artifacts. 
<img width="1258" alt="scene" src="https://user-images.githubusercontent.com/35488694/86278642-99013f00-bb8d-11ea-87ca-f394fa9709d5.png">

**Comment by progschj** [comment]
It just still seems to me like the blender rendering somehow is flat shaded? When I just load the model as is and apply a texture and normal map I get this: 
![couch_blender](https://user-images.githubusercontent.com/1257680/86374429-d85e8700-bc84-11ea-9741-e78aa10e1b5d.png)

When I switch to flat shading I get this:
![couch_flat](https://user-images.githubusercontent.com/1257680/86376442-499f3980-bc87-11ea-833b-3e5c9a46fc82.png)

There might be something additional going on with the specific banding. I'll have a look at your code.

**Comment by progschj** [comment]
The normals and faces aren't consistently oriented. On the side parts they point inwards but on the cushion outwards.

![couch_orientation](https://user-images.githubusercontent.com/1257680/86380807-d4cefe00-bc8c-11ea-8292-f0466f0e156e.png)

**Comment by micaeltchapmi** [comment]
@progschj We use nodes (PrincipledBSDF shader) in blender to load the CCOTexture maps. This is the
[code](https://drive.google.com/drive/folders/1MtPg5zadM-VYBj1wO-O-tJ4dass3f_ab?usp=sharing) we used to create those nodes. 

I fixed the normals in Blender
<img width="391" alt="Screen Shot 2020-07-03 at 12 12 45 AM" src="https://user-images.githubusercontent.com/35488694/86442124-23e35600-bcc2-11ea-917e-787c9ec3a143.png">
<img width="734" alt="Screen Shot 2020-07-03 at 12 13 20 AM" src="https://user-images.githubusercontent.com/35488694/86442138-2b0a6400-bcc2-11ea-9723-c0d4bc32a69c.png">

and here is the object with fixed normals: [couch_33_fixed.obj.zip](https://github.com/NVIDIA/VisRTX/files/4868699/couch_33_fixed.obj.zip)


Here is an image of the couch with fixed normals rendered with CCOTextures materials in blender using this [code](https://drive.google.com/drive/folders/1MtPg5zadM-VYBj1wO-O-tJ4dass3f_ab?usp=sharing)
<img width="411" alt="Screen Shot 2020-07-03 at 12 19 45 AM" src="https://user-images.githubusercontent.com/35488694/86443879-be449900-bcc4-11ea-84e8-9d195ec3fd0d.png">

When we render the same couch with MDL materials using the [code](https://github.com/NVIDIA/VisRTX/files/4726275/test_darkshades.zip) I sent earlier on, we still see the dark bands on the couch.
<img width="338" alt="Screen Shot 2020-07-03 at 12 16 34 AM" src="https://user-images.githubusercontent.com/35488694/86444189-41fe8580-bcc5-11ea-9ee8-07a875d9cab8.png">

**Comment by progschj** [comment]
> Here is an image of the couch with fixed normals rendered with CCOTextures materials in blender using this code

That code seems to use this uvmap function which does: `bpy.ops.object.modifier_add(type='EDGE_SPLIT')`
Which seems consistent with everything above? Do you expect VisRTX to apply an edge split/use flat shading?

**Comment by micaeltchapmi** [comment]
@progschj  I removed the `uvmap` function in `loadcouch.py` and commented out the edge split modifier on line 287 in `materials/brender/brender/mesh.py`. Here is the [updated code](https://drive.google.com/drive/folders/1LUj0NXZG73oQN00lDqbh5mmfjnqMw5Vz?usp=sharing) and below is the difference with and without the edge split modifier.

Smooth (without edge split)
<img width="408" alt="Screen Shot 2020-07-03 at 11 45 36 AM" src="https://user-images.githubusercontent.com/35488694/86492997-b1579200-bd24-11ea-8907-250666826755.png">

Flat (with edge split)
<img width="411" alt="Screen Shot 2020-07-03 at 12 19 45 AM" src="https://user-images.githubusercontent.com/35488694/86493025-c2a09e80-bd24-11ea-8df6-f7c2ca07f97a.png">

Here is another example where the difference is more obvious:

Smooth (without edge split)

<img width="405" alt="Screen Shot 2020-07-03 at 12 13 48 PM" src="https://user-images.githubusercontent.com/35488694/86493660-33e15100-bd27-11ea-8dd9-6b8454f5f9a9.png">

Flat (with edge split)
<img width="448" alt="Screen Shot 2020-07-03 at 12 15 04 PM" src="https://user-images.githubusercontent.com/35488694/86493684-43609a00-bd27-11ea-90e3-67b4c5a77263.png">

In both cases, the dark bands do not appear on the couch so the issue does not appear to be flat vs smooth shading.

**Comment by micaeltchapmi** [comment]
@progschj In addition to the dark bands, the mdl rendering also seems to result in geometric deformations in some parts of the couch.
<img width="338" alt="couch_dark_bands_original_red_deform_annot" src="https://user-images.githubusercontent.com/35488694/86521778-e25dc280-be09-11ea-9c29-f21ab3ef45df.png">

**Comment by progschj** [comment]
Right, so what appears to happen is that the light is sampled based on the hemisphere defined by the normal. In this case the normals are "rotating" so much over the face that the tangent space derived from said interpolated normal causes issue.

Can you try changing

https://github.com/NVIDIA/VisRTX/blob/master/src/Pathtracer/Pathtracer.cu#L593
```cpp
optix::Onb onb(prd.normal);
```
to
```cpp
optix::Onb onb(prd.geometricNormal);
```
and see if that solves your issue?

I'll have to check for other side effects before committing this to the public source.

**Comment by micaeltchapmi** [comment]
@progschj Thanks for the suggestion. I changed the line of code like you suggested and here is the result on the couch.

Before
<img width="338" alt="Screen Shot 2020-07-03 at 12 16 34 AM" src="https://user-images.githubusercontent.com/35488694/86444189-41fe8580-bcc5-11ea-9ee8-07a875d9cab8.png">
After
<img width="306" alt="Screen Shot 2020-07-10 at 8 22 36 AM" src="https://user-images.githubusercontent.com/35488694/87183681-6ba64680-c29b-11ea-9195-12805bb251db.png">

The change has helped fix the dark bands in the middle of the object.  
However, the geometric deformations are still appearing on the couch when rendered with certain materials (Bubinga_teak_oiled).
<img width="308" alt="Screen Shot 2020-07-10 at 11 42 53 AM" src="https://user-images.githubusercontent.com/35488694/87188195-40275a00-c2a3-11ea-9fa6-47b435434a1f.png">


Here is a more obvious example of this issue with this [table](https://github.com/NVIDIA/VisRTX/files/4904924/table_98.obj.zip)

Below is the table rendered with CC0Textures
<img width="353" alt="Screen Shot 2020-07-10 at 10 38 41 AM" src="https://user-images.githubusercontent.com/35488694/87184390-c68c6d80-c29c-11ea-91f9-2b22bc813abb.png">


And here is the rendering of the table with MDL material(Bubinga_teak_oiled)
<img width="212" alt="Screen Shot 2020-07-10 at 10 46 30 AM" src="https://user-images.githubusercontent.com/35488694/87184262-8e852a80-c29c-11ea-8d8e-48dcb673b6ad.png">

**Comment by progschj** [comment]
From what I can tell that is caused by the interpolated normals diverging severely from the actual geometry normals. Since the vertex normals are at such extreme angles (45° off at the edge of many polygons) some of them point away from the camera even thou we are seeing the front face of the polygon. So as far as the material model is concerned the ray is hitting the surface from the back. There is some code here:

https://github.com/NVIDIA/VisRTX/blob/master/src/Pathtracer/Pathtracer.cu#L1087

that attempts to prevent that by using the face normal instead of the interpolated (unphysical) one in those situations.

If you comment out
```cpp
	if (optix::dot(prd.normal, ray.direction) > 0.0f)
		prd.normal = prd.geometricNormal;
```
it will look less glitchy but the affected regions will just be black.

![image](https://user-images.githubusercontent.com/1257680/87202071-1e0ff500-c300-11ea-8758-7412e7820d92.png)

The jaggedness of these is caused by the somewhat suboptimal tessellation of these models together with their extreme normals.

**Comment by progschj** [comment]
One way to "hack it" would be to replace the above code with something like:
```cpp
	float blend_range = 10.0f;
	float NdotD = optix::dot(prd.normal, ray.direction);
	float GNdotD = optix::dot(prd.geometricNormal, ray.direction);
	prd.normal = optix::lerp(prd.normal, prd.geometricNormal, optix::clamp((NdotD-GNdotD)*blend_range, 0.0f, 1.0f));
```
so it smoothly transitions into using the face normal instead of doing so abruptly. This is also unphysical and results in almost flat shading for this example. So I'm not sure it should be the default behavior?

**Comment by progschj** [comment]
2dfe38b7d12db26614fa34ce2ce03e268a239864 removes the normal adjusting code that caused the striping discontinuities.
