### ISSUE TITLE
How to adjust the focal length of the perspective Camera?

### ISSUE THREAD

**Issue by micaeltchapmi** [NVIDIA/VisRTX#20]
Hi,

I would like to know how to increase or decrease the field of view of the camera or the focal length after placing the Camera at a fixed location. 

I would like my camera to be fixed at location (0.2, 0.8, 0.56) so I set it using `perspectiveCamera->SetPosition(Vec3f(0.2, 0.83, 0.56));`. How can I adjust the field of view of the camera at this location? Do you currently have support for this?

Thanks,

Micael

**Comment by progschj** [comment]
`PerspectiveCamera::SetFovY` Sets the horizontal field of view in degrees.

**Comment by tbiedert** [comment]
And for depth of field there is `PerspectiveCamera::SetFocalDistance(float focalDistance)` and `PerspectiveCamera::SetApertureRadius(float apertureRadius)`.
