### ISSUE TITLE
MDL_ARGUMENT_BLOCK_SIZE should be 368 for 16 byte struct alignment

### ISSUE THREAD

**Issue by hugebean** [NVIDIA/VisRTX#21]
Hello 
Some MDL material thrown unknown error when it is 372 bytes,  there are 7 program id(int) and 1 hasArgBlock(int), so argBlock's length shoud be 368.

**Comment by progschj** [comment]
Thanks for reporting this. Can you share a way to reproduce this? What material causes that issue?

**Comment by hugebean** [comment]
> Thanks for reporting this. Can you share a way to reproduce this? What material causes that issue?

MDL
module: mdl/nvidia/vMaterial/Design/Ceramic/Porcelain_Cracked
material: cracked_porcelain_china

All objects in my scene use Principled material , class compile type.
I found that when I used Porcelain_Crackedto replace a Principled  material which was located in the buffer pool with an even index. An unknown error will be thrown

I tested a lot of materials, some happened, some didn't

**Comment by progschj** [comment]
4464e8ed3e940377519a3751c691af0924e3c51c should fix this
