### ISSUE TITLE
CUDA 11 support

### ISSUE THREAD

**Issue by mathstuf** [NVIDIA/VisRTX#23]
The `sm_30` arch is no longer supported, but it is forced in the flags in this project. What is the recommended replacement? Should CUDA 11 be detected and the arch upgraded to something newer?

**Comment by progschj** [comment]
The easiest is probablay to just leave the arch off or set it to the actual target architecture. I'm trying to figure out if setting sm_30 is required in some combination of older OptiX/CUDA versions.

**Comment by progschj** [comment]
In c37a56e00f76186c92163a4d880c61101eeb1539 I went with the conservative approach of removing the arch specification only for CUDA 11 and up.
