### ISSUE TITLE
Instancing, Transformations

### ISSUE THREAD

**Issue by CobraCalle** [NVIDIA/VisRTX#24]
Hello,

at first: Thank you very much for this great work. I`ve written a .NET-Wrapper for VisRTX, and we what to use this for our own research for a server based, high end, product configurator.

Are there any plans to support instacing? At the moment (as I could see) there is no method to load a geometry one time, and reuse it many times... is that correct? So for example, if we would like to render a sofa that consists of three pillows, we would like to load the geometry for that pillow only one time and reuse it.

That points me directly to the next question... as I can see from the header files, there is currently no way to transform / translate a loaded geometry at the moment... is that correct?

Does that really mean I have to reload the pillow (in the above example) for every instance, and have to change the vertices directly?

Thank you for your help

**Comment by jeffamstutz** [comment]
Hi,

The `v0.1.x` implementation is deprecated in favor of the new ANARI based version (`v0.2.0+`). Instancing is fully supported for geometries and volumes, and light instancing will come in the future. You can find out more about ANARI here: https://www.khronos.org/api/index_2017/anari

Cheers!
