### ISSUE TITLE
Assertion Failed in libmdl_sdk.dll

### ISSUE THREAD

**Issue by countywest** [NVIDIA/VisRTX#25]
![error](https://user-images.githubusercontent.com/36671481/106233487-01a2be00-623a-11eb-9026-90c969dfa47c.png)

Hello!
I have an assertion error message when using the `Release VisRTX v0.1.6` in Windows.
Rendering codes work well, but the assertion error occurs after finishing rendering loop and exiting the process when running the samples using MDL-SDK(`SampleMDL`, `SampleMeshViewer`, `SampleVolume`).
The exception error occurs in the `MDL-SDK-2019.1.4/src/mdl/jit/llvm/dist/lib/Support/ManagedStatic.cpp, line 64` in the function `void ManagedStaticBase::destroy()`.
When I run the process using MDL-SDK in Linux there was no runtime error message, but there is in the Windows.
Is this a solvable problem?

**Comment by jeffamstutz** [comment]
Hi,

The `v0.1.x` implementation is deprecated in favor of the new ANARI based version (`v0.2.0+`), which no longer uses MDL. MDL may be brought back as an optional component in the future, but that is not yet decided.

Cheers!
