### ISSUE TITLE
Provisional ANARI 1.0 API support?

### ISSUE THREAD

**Issue by oscarbg** [NVIDIA/VisRTX#26]
Hi,
seems spec 1.0 API has been released..
and an Nvidia implementation seems coming soon based on VisRTX:
"There are also early ANARI implementations in development by AMD, Intel and NVIDIA that will provide access to their Radeon ProRender, OSPRay, and VisRTX rendering engines respectively"
from:
"https://www.khronos.org/news/press/khronos-announces-public-release-of-the-anari-1.0-provisional-specification"

so just opening issue to get notified when is posted.. :-)

thanks..

**Comment by jeffamstutz** [comment]
The new `v0.2.0` release has you covered! However, pretty much EVERYTHING changed compared to the previous implementation, but this is just the beginning. Still a _ton_ of things left to do, but hopefully what's up is quite usable for now!
