### ISSUE TITLE
Enabling color and depth channels on a Frame inconsistent with Spec

### ISSUE THREAD

**Issue by griffin28** [NVIDIA/VisRTX#33]
The enabling of the `color` and `depth` channels on a `Frame` is inconsistent with the spec. Setting the observable type of the aforementioned channels is supposed to be sufficient for enabling those channels. e.g.,

```
anari::setParameter(anariDevice, anariFrame, "color", ANARI_UFIXED8_RGBA_SRGB);
anari::setParameter(anariDevice, anariFrame, "depth", ANARI_FLOAT32);
```

However, if you don't also set two additional parameters on the Frame, `channelColor` and `channelDepth`, to **true** the `color` and `depth` channels won't be enabled. Also, the `channelColor` and `channelDepth` parameters are not documented in the spec.

**Comment by jeffamstutz** [comment]
This is now fixed in `main`, thanks!
