### ISSUE TITLE
pathtracer renderer subtype produces same image as debug subtype

### ISSUE THREAD

**Issue by griffin28** [NVIDIA/VisRTX#34]
There may be a copy/paste error with the `pathtracer` renderer subtype. It renders the same image as the `debug` renderer subtype. The rest of the renderer subtypes work as expected.

This is what the rendering should look like (`raycast`):
![screenshot2](https://user-images.githubusercontent.com/26772741/182724460-1a0cf35e-418e-4ced-8de3-1c9593338067.png)

Here's what selecting the `pathtracer` subtype produces:
![screenshot1](https://user-images.githubusercontent.com/26772741/182724539-c85081b6-f71f-4f59-a224-956bcc9aade5.png)

**Comment by jeffamstutz** [comment]
Great catch, the json definition for the renderers incorrectly had `pathtracer` in it. Fixed now on the `next_release` branch, thanks!
