### ISSUE TITLE
Need to support other color formats with image2D samplers

### ISSUE THREAD

**Issue by griffin28** [NVIDIA/VisRTX#35]
Only Float 32-bit float data is currently supported by image2D samplers. Most VTK datasets will use the `ANARI_UFIXED8_VEC4` color format.

These color formats are also important for VTK:

```
ANARI_UFIXED8
ANARI_UFIXED8_VEC2
ANARI_UFIXED8_VEC3
ANARI_UFIXED8_VEC4

ANARI_UFIXED8_R_SRGB
ANARI_UFIXED8_RA_SRGB
ANARI_UFIXED8_RGB_SRGB
ANARI_UFIXED8_RGBA_SRGB

ANARI_UFIXED16
ANARI_UFIXED16_VEC2
ANARI_UFIXED16_VEC3
ANARI_UFIXED16_VEC4
```

**Comment by jeffamstutz** [comment]
This is now implemented on the `next_release` branch, thanks!
