### ISSUE TITLE
Adding git tags?

### ISSUE THREAD

**Issue by mathstuf** [NVIDIA/VisRTX#4]
If there is going to be a version bump per commit, could tags be added?

Also, if you're planning on doing a release per commit (or per merge), I recommend looking at something like [semantic-release](https://github.com/semantic-release/semantic-release). However, it looks like it needs hosted somewhere.

**Comment by tbiedert** [comment]
Thanks for the suggestions!  

VisRTX is still quite in flux as we all are working towards the ParaView RC, and I’m trying to iron out issues as soon as they come up.

Not sure yet what the ideal release mechanics should look like, but I’ll definitely look into tagging each release properly!
