### ISSUE TITLE
Need to support nearest and linear filter for all Volume data types

### ISSUE THREAD

**Issue by griffin28** [NVIDIA/VisRTX#40]
Need to support nearest and linear filtering (ideally cubic too) for all Volume data types. Currently nearest and linear filtering is only supported for float Volume data. Volume data of type **int** (`uint8`, `uint16`, `int16`) using anything but nearest filtering will result in an error.

**Comment by jeffamstutz** [comment]
Implemented on `next_release` branch in 83be7d2.
