### ISSUE TITLE
OpenGL device does not build on Windows

### ISSUE THREAD

**Issue by UX3D-haertl** [NVIDIA/VisRTX#43]
OpenGL::OpenGL needs to be changed to OpenGL::GL on Windows, as far as I know.
When I change it, I get these additional errors:
![grafik](https://github.com/NVIDIA/VisRTX/assets/50208655/985fc2a8-a22c-441d-ae77-ad525810ba81)

**Comment by jeffamstutz** [comment]
This is fixed in the latest release.
