### ISSUE TITLE
releasing device causes segfault if device was not used

### ISSUE THREAD

**Issue by ExpandingMan** [NVIDIA/VisRTX#51]
[This MWE](https://gist.github.com/ExpandingMan/8c66fcc233695ccf9241f323a6f5604e) results in a segmentation fault on the call to `anariRelease(dev, dev)`.  As far as I can tell, this only occurs if the `ANARIDevice` object is "unused", i.e. has not been used in the creation of a child object such as a camera.  Note that I only see log output when creating such an object, which suggests to me that the `ANARIDevice` is in an uninitialized state when `anariRelease` is called, presumably resulting in the segfault.

It's not entirely clear to me that this is *not* intended behavior, but it seems slightly problematic as programs will have to guess whether the `ANARIDevice` has been properly initialized to release it.

**Comment by jeffamstutz** [comment]
Ooof, yeah that's a bug. I just pushed a fix on the `next_release` branch. If that works for you, I'll cut a `v0.6.1` release. Thanks!

**Comment by ExpandingMan** [comment]
Seems to have fixed the problem, thanks!  Don't know whether you want to close this now or when it gets tagged, so I'll leave it to you to close.
