### ISSUE TITLE
What's the minimum hardware requirement ?

### ISSUE THREAD

**Issue by ColinChargyBentley** [NVIDIA/VisRTX#52]
Hi,
I haven't seen anywhere in the doc, could you explicit the minimal hardware required to run VisRTX ?
Regards,
Colin Chargy

**Comment by jeffamstutz** [comment]
Hi Colin! Any Maxwell or newer GPU should work, as the only requirement is that OptiX can run on the GPU. I can mention this in the README.

Are you experiencing any issues getting VisRTX to run on your hardware?
