### ISSUE TITLE
Sampler `transform` needed

### ISSUE THREAD

**Issue by stukowski** [NVIDIA/VisRTX#53]
It would be great if you could make the Transform sampler work in the `scivis` renderer. My attempts to use it failed so far, and a look into the source code gives me the impression that this sampler type is not fully implemented yet or does something unexpected. The `outTransform` parameter has no effect. I would like to use it to convert per-primitive transparency values to opacity values (`opacity = 1 - transparency`). So roughly like this:

```c++
AnariHandle<anari::Sampler> sampler(deviceHandle(), "transform");
sampler.setParameter("inAttribute", "attribute0");
sampler.setParameter("outTransform", std::array<std::array<float, 4>, 4>{{
    { -1.0f, 0.0f, 0.0f, 0.0f },
    {  0.0f, 1.0f, 0.0f, 0.0f },
    {  0.0f, 0.0f, 1.0f, 0.0f },
    {  0.0f, 0.0f, 0.0f, 1.0f }}});
sampler.setParameter("outOffset", std::array<float, 4>{{ 1.0f, 0.0f, 0.0f, 0.0f }});
sampler.commitParameters();

AnariHandle<anari::Material> material(deviceHandle(), "matte");
material.setParameter("color", "color");
material.setParameter("alphaMode", "blend");
material.setParameter("opacity", std::move(sampler));
material.commitParameters();
```

**Comment by stukowski** [comment]
Setting `transform` instead of `outTransform` seems to work - as a non-standard interim solution.

**Comment by jeffamstutz** [comment]
Thanks for catching this! I just pushed a fix to `next_release`. I'll cut a patch release soon, but could you try out the fix on your end?

**Comment by stukowski** [comment]
Yes, with the new fix the transform sampler works as expected now. Thanks!
