### ISSUE TITLE
VisGL with EGL MSVC build error

### ISSUE THREAD

**Issue by ColinChargyBentley** [NVIDIA/VisRTX#61]
Hi,
On MSVC, near and far are reserved keywords (https://github.com/cython/cython/issues/1959), so building VisGL with EGL throws these errors :
devices\gl\generated\VisGLObjects.h(289,33): error C2208: 'visgl::Parameter<1068>': no members defined using this type
devices\gl\generated\VisGLObjects.h(290,32): error C2208: 'visgl::Parameter<1068>': no members defined using this type
devices\gl\generated\VisGLObjects.h(319,33): error C2208: 'visgl::Parameter<1068>': no members defined using this type
devices\gl\generated\VisGLObjects.h(320,32): error C2208: 'visgl::Parameter<1068>': no members defined using this type

Can I rename near and far to nearDistance and farDistance ?

Regards,
Colin Chargy

**Comment by jeffamstutz** [comment]
@progschj what ideas do you have for this with the code generation that VisGL uses?

**Comment by progschj** [comment]
It seems like they are actually defines that can be undeffed without consequence. https://stackoverflow.com/questions/118774/is-there-a-clean-way-to-prevent-windows-h-from-creating-a-near-far-macro

**Comment by progschj** [comment]
I tried to address this issue in the next release branch https://github.com/NVIDIA/VisRTX/commit/8af2eed799757a861f33c80453bcee0172a78a11
