### ISSUE TITLE
Issue with Lighting When Applying Non-Identity Transform

### ISSUE THREAD

**Issue by nnn911** [NVIDIA/VisRTX#68]
I am experiencing unexpected lighting artifacts when applying a transformation matrix other than the identity matrix in an Anari instance. Below are two images: the first one shows the scene with the original configuration, and the second one shows the same scene rotated by 180 degrees, where the lighting issue is apparent.

<img src="https://github.com/NVIDIA/VisRTX/assets/60605180/f56c96bc-7f01-42cb-9465-92df1d245891" height="300" title="scene rendered with unity identity transformation matrix">
<img src="https://github.com/NVIDIA/VisRTX/assets/60605180/3329a307-6a12-41b4-b8d4-388ad0ed8b13" height="300" title="scene rendered with unity non-identity transformation matrix">

## Lights
The scene is illuminated by two light sources: an ambient light and a directional light. These are set up using the following snippets:

Ambient light:
```cpp
AnariHandle<anari::Renderer> renderer(deviceHandle(), "visrtx");
renderer.setParameter("background", std::array<float, 4>{{0.0f, 0.0f, 0.0f, 0.0f}});
renderer.setParameter("ambientSamples", ambientSamples);
renderer.setParameter("ambientRadiance", ambientRadiance);
renderer.setParameter("ambientColor", ambientColor);
renderer.commitParameters();
```

Directional light:
```cpp
AnariObjectArray<anari::Light> lights(deviceHandle());
AnariHandle<anari::Light> light = lights.emplace_back("directional");
light.setParameter("direction", lightDir);
light.setParameter("irradiance", irradiance);
light.commitParameters();
```

## Instance
Here is the code snippet for setting up the instance:
```cpp
instance = AnariHandle<anari::Instance>(deviceHandle(), "transform");
instance.setParameter("group", group);
instance.setParameter("id", instanceId);
instance.setParameter("transform", anari::std_types::mat4{{
    {modelTM(0,0), modelTM(1,0), modelTM(2,0), 0.0f},
    {modelTM(0,1), modelTM(1,1), modelTM(2,1), 0.0f},
    {modelTM(0,2), modelTM(1,2), modelTM(2,2), 0.0f},
    {modelTM(0,3), modelTM(1,3), modelTM(2,3), 1.0f}
}});
instance.commitParameters();
```

With `modelTM` set as the identity matrix:
```
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
```
the lighting appears correct, and the scene is rendered as expected, as shown in image (1).

However, upon applying a rotation with the following `modelTM`:
```
-1  0 0 0
 0 -1 0 0
 0  0 1 0
 0  0 0 1
```
I observe unexpected lighting artifacts, visible in image (2). Camera and direct light directions remain unchanged compared to image (1).

## Environment / versions
- Windows 11
- NVIDIA GPU Computing Toolkit CUDA v12.3
- OptiX 7.6
- VisRTX 0.6.2 (branch `next_release` @72b0e4b)
- Anari SDK 0.8.0 (branch `next_release` @bf50ded)

##
Any insights into these lighting artifacts would be appreciated.

**Comment by jeffamstutz** [comment]
This seemed isolated to sphere geometry normals, where in [this recent change](f389833) I fixed it by unifying it with all other primitives. That seems to have fixed it. Let me know if you still experience any issues!
