### ISSUE TITLE
Ambient light question

### ISSUE THREAD

**Issue by stukowski** [NVIDIA/VisRTX#70]
I am wondering if there is a way to define an ambient light that illuminates *every* surface - including interior surfaces that are not accessible to AO? For example, I would like to brighten up this cavity (without placing a separate light source inside the cavity):

![cavity_example](https://github.com/NVIDIA/VisRTX/assets/16364980/4636e7fb-a492-4253-a919-347a19636b5c)

This scene uses a (weak) directional light and an `ambientRadiance` value of 1.0. Material is `matte`.

**Comment by jeffamstutz** [comment]
You could use the `ambientOcclusionDistance` parameter to shorten AO rays, which is probably what you want. Alternatively setting `ambientOcclusionSamples` to `0` will turn off AO altogether while still adding ambient lighting.
