### ISSUE TITLE
VisRTX/CUDA deployment issue

### ISSUE THREAD

**Issue by stukowski** [NVIDIA/VisRTX#72]
I am facing the following issue: 

Our application (making use of the VisRTX renderer) works with an NVIDIA A5000 board without problems on our Ubuntu Linux development machine. When we deploy the compiled application binaries to an end user's computer, which also has an A5000, the end user sees the following error during VisRTX initialization:

```
TERMINATING DUE TO UNCAUGHT ANARI EXCEPTION (std::exception): This program was not compiled for SM 86
: cudaErrorInvalidDevice: invalid device ordinal
terminate called after throwing an instance of 'thrust::system::system_error'
what(): This program was not compiled for SM 86
: cudaErrorInvalidDevice: invalid device ordinal
Aborted (core dumped)
```

What are the possible reasons for this error? Since `libanari_library_visrtx.so` has been compiled with `-DCMAKE_CUDA_ARCHITECTURES=all` (CUDA Toolkit 12.2) and SM 86 support should be present, I am wondering whether incompatible cuda shared libraries on the end user's computer may be responsible for this. 

I checked which shared libraries get loaded at runtime (on the development machine):

```
libanari.so.0
libanari_library_visrtx.so
/lib/x86_64-linux-gnu/libcuda.so.1
/usr/local/cuda/targets/x86_64-linux/lib/libcurand.so.10
/lib/x86_64-linux-gnu/libnvoptix.so.1
/lib/x86_64-linux-gnu/libcuda.so
/lib/x86_64-linux-gnu/libnvidia-rtcore.so.535.104.12
/lib/x86_64-linux-gnu/libnvidia-ml.so.1
```

We currently deploy only `libanari.so.0` and `libanari_library_visrtx.so` with the application. Which of the other ones may be (and should be) shipped with the application? My guess is that `libcurand.so.10` is a good candidate, but I am not sure if it is sufficient. It would be great if you could confirm this.

EDIT: 

The following libs get loaded on the target machine of the end user:

```
/lib/x86_64-linux-gnu/libcuda.so.1
/usr/local/cuda/lib64/libcurand.so.10
/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1
/lib/x86_64-linux-gnu/libnvoptix.so.1
/lib/x86_64-linux-gnu/libcuda.so
/lib/x86_64-linux-gnu/libnvidia-rtcore.so.525.116.04
/lib/x86_64-linux-gnu/libnvidia-ml.so.1
```
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.116.04   Driver Version: 525.116.04   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:AF:00.0  On |                  N/A |
|  0%   34C    P8    34W / 350W |   1144MiB / 24576MiB |      8%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
(the user may be using an RTX 3090, not A5000, in this case.)

**Comment by stukowski** [comment]
By the way, is it possible for the application to handle this type of error more gracefully? I mean the "TERMINATING DUE TO UNCAUGHT ANARI EXCEPTION" part.

**Comment by jeffamstutz** [comment]
> Which of the other ones may be (and should be) shipped with the application? 

My intuition is that static linking these might help -- could you see if replacing `CUDA::curand` with `CUDA::curand_static` helps?

I am also not sure if building with newer CUDA toolkit libraries will run with older toolkit libraries, but I would think going the other direction would work.

> By the way, is it possible for the application to handle this type of error more gracefully? I mean the "TERMINATING DUE TO UNCAUGHT ANARI EXCEPTION" part.

The short answer is yes -- the termination part gets encountered when an uncaught exception gets thrown and the ANARI frontend library catches it (i.e. doesn't let it leak to C). Reaching that point means that there's an exception case that was thrown and unhandled by VisRTX. I'll have to look into the best solution, but in general problem is that CUDA was initialized successfully but ends up running on a GPU that it can't use...this should be caught on device initialization instead of failing on a Thrust call.

**Comment by stukowski** [comment]
We've now deployed `libcurand.so.10` from the build machine to the end user's computer and double-checked that our version of the lib gets loaded at runtime -- this did *not* make any difference though, the exception still occurs. This makes me think that using `CUDA::curand_static` wouldn't make much of a difference either.

On the other hand:

We've learned in the meantime that VisRTX works on the end user's system when we build the application and VisRTX in a conda environment (using conda-forge's build toolchain, CUDA libs and toolkit wrapper). So I looked into possible differences between our regular build procedure and what happens when VisRTX is built in the conda environment. Interestingly, `libanari_library_visrtx.so` no longer has a runtime dependency on `libcurand.so` in this case (checked via `ldd`) - even though `libcurand.so` is definitely part of the linker command line! I observed that the conda toolchain implicitly adds `-Wl,--as-needed` to the command line, allowing the linker to ignore, i.e., not link against, some of the libraries supplied on its command line if they are not actually used by the shared library that is being created.

I am not sure, but an explanation might be that the cuRAND functions VisRTX needs get all inlined and then the linker can drop the runtime dependency completely. What do you think?

It still remains to be shown whether this difference (and libcurand.so) has anything to do with the original issue.

**Comment by jeffamstutz** [comment]
Getting back to this -- I can confirm that building with the CUDA that comes with Ubuntu 22.04 (11.5.) can be successfully run with CUDA libraries found on Ubuntu 23.10 (12.0). I did this by building with an Ubuntu 22.04 container, then copying `libanari_library_visrtx.so` to my Ubuntu 23.10 host and running there. Note that the build environment doesn't actually need the driver to function (my container did not have the driver installed, nor GPU pass-through setup). As long as you set `CMAKE_CUDA_ARCHITECTURES` to the desired value(s) for the target machine, it should be compatible.

To me this confirms that building with an _older_ CUDA should run with a newer version.

**Comment by stukowski** [comment]
I can now confirm that building VisRTX with an older CUDA toolkit version seems to solve the problem (error "This program was not compiled for SM 86"). 

Our own Ubuntu test machine, which could run our VisRTX executables in the past, started failing with this error after the build machine (a dockerized conda-forge build environment in this case) was upgraded to CUDA 12.3. Then, after forcing the build to use old CUDA 12.0, the test machine was able to run the executable without problems again. All this without changes to the driver or hardware installed in the test machine. 

I think this shows that we can indeed mitigate this kind of error by using a reasonably old CUDA toolkit version to build VisRTX. We can close this issue for now, I would say. I will reopen it in case this solution does not also solve the problem on the computers of our end users.

**Comment by jeffamstutz** [comment]
Sounds good, thanks for trying those ideas!
