### ISSUE TITLE
Cannot compile renderpipeline sample on Windows

### ISSUE THREAD

**Issue by PaddiM** [NVIDIA/VisRTX#76]
Hi, 

I have 2 errors when compiling renderpipeline project on Windows 10 (Renderpass.cu) building main branch.

- On Windows, the enclosing parent function ("thrustCompositeFrame") for an extended __device__ lambda cannot have internal or no linkage	renderpipeline	D:\Projekte\nvidia\VisRTX\Anari\VisRTX\examples\renderpipeline\RenderPass.cu	line 103		
- On Windows, the enclosing parent function ("thrustComputeOutline") for an extended __device__ lambda cannot have internal or no linkage	renderpipeline	D:\Projekte\nvidia\VisRTX\Anari\VisRTX\examples\renderpipeline\RenderPass.cu	line 121		

OS: Windows 10
Visual Studio 2022 17.10.0
CUDA 12.5

Best regards,

Patrik

**Comment by jeffamstutz** [comment]
Thanks for the bug report! I don't encounter this on Linux, so this may be an issue specific to Windows linkage (that I don't understand the detail). By the look of the error, does it compile if you remove the `static` keyword on those functions? If that does indeed fix it, then I can push a fix ASAP...thanks!

**Comment by PaddiM** [comment]
Yes - this fixes the error.

Found 2 other problems:

* RenderPass.h - variable "GLuint" is not a type name	128	
Fix: add
```
#ifdef _WIN32
#include "Windows.h"
#endif
```
before
```// OpenGL
#include <GL/gl.h>
// CUDA
```

* Error	C2039	'iota': is not a member of 'std'	pipeline_example.cpp	101		
Fix: add
```
#include <numeric>
```


No more compiler errors...

Regards,

Patrik

**Comment by jeffamstutz** [comment]
Ok, I'll incorporate right away -- thank you!

**Comment by PaddiM** [comment]
Thanks for the fast support!

**Comment by jeffamstutz** [comment]
Fixes are now on the `next_release` branch -- please reopen if you continue to see any issues.
