### ISSUE TITLE
Hide Geometry？

### ISSUE THREAD

**Issue by dwlcj** [NVIDIA/VisRTX#8]
How to Hide a geometry with Emissive Material?
like Light SetVisible.

**Comment by tbiedert** [comment]
That is currently not possible, sorry!  No support for mesh lights at this stage.

**Comment by tbiedert** [comment]
However, if your scene layout permits, you could place the emitting geometry behind a primary rays-only clipping plane.  

Can you give some more details of your use case? (We can also take this offline if you prefer).

**Comment by dwlcj** [comment]
Hello, Tim.
My Code：

VisRTX::BasicMaterial* springMaterial = context->CreateBasicMaterial();
springMaterial->SetEmissive(Vec3f(1.0, 1.0, 1.0));
springMaterial->SetLuminosity(2.0);
springMaterial->SetOpacity(0.0);//????
//set Emissive Material
triangleGeo->SetMaterial(springMaterial);
springMaterial->Release();

In This Code triangleGeo is hide,But Emissive Material failure.

**Comment by dwlcj** [comment]
Another question：
Do VisRTX Support IES lighting?

**Comment by tbiedert** [comment]
Yes, that’s currently expected behavior.  In the basic material, emission is only added if there is a hit. But the lower opacity, the lower the probability for a hit (it’s cut-out opacity).

VisRTX does not support light profiles.

**Comment by dwlcj** [comment]
Thanks, Tim.
