### ISSUE TITLE
Possible bug in renderer initialization code

### ISSUE THREAD

**Issue by stukowski** [NVIDIA/VisRTX#82]
I came across [this code](https://github.com/NVIDIA/VisRTX/blob/21e4db5fa74f235a1a0062b0caeb072065e7e626/devices/rtx/frame/Frame.cu#L306C1-L313C13) in `Frame.cu`:

```
    OPTIX_CHECK(optixLaunch(m_renderer->pipeline(),
        state.stream,
        (CUdeviceptr)deviceData(),
        payloadBytes(),
        m_renderer->sbt(),
        checkerboarding() ? (hd.fb.size.x + 1) / 2 : hd.fb.size.x,
        checkerboarding() ? (hd.fb.size.y + 1) / 2 : hd.fb.size.y,
        1));
```

I'm not sure, but it looks like `m_renderer->pipeline()` may return a null pointer, because the pipeline is created only after `m_renderer->sbt()` is called for the first time.

**Comment by jeffamstutz** [comment]
While I haven't seen this create issues, it certainly looks like UB. I've fixed this in bc33718, thanks!
